# Generated by Django 3.1.4 on 2021-02-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='link',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='table',
            name='pdf_doc',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
