# Generated by Django 3.1.4 on 2021-02-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namelanguage', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.ManyToManyField(max_length=255, to='user.Language'),
        ),
    ]
