# Generated by Django 3.1.4 on 2021-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210206_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
